# src/zndraw_joblib/__init__.py
"""ZnDraw Job Management Library."""

from zndraw_joblib.client import Category, ClaimedTask, Extension, JobManager
from zndraw_joblib.dependencies import (
    FrameRoomCleanup,
    FrameRoomCleanupDep,
    JobLibSettingsDep,
    ResultBackend,
    ResultBackendDep,
    WritableRoomDep,
    get_frame_room_cleanup,
    get_joblib_settings,
    get_result_backend,
    get_tsio,
    request_hash,
    validate_room_id,
    verify_writable_room,
)
from zndraw_joblib.events import (
    Emission,
    FrozenEvent,
    JobsInvalidate,
    JoinJobRoom,
    JoinProviderRoom,
    LeaveJobRoom,
    LeaveProviderRoom,
    ProviderRequest,
    ProviderResultReady,
    ProvidersInvalidate,
    TaskAvailable,
    TaskStatusEvent,
    build_task_status_emission,
    emit,
)
from zndraw_joblib.exceptions import (
    Forbidden,
    InternalJobNotConfigured,
    InvalidCategory,
    InvalidRoomId,
    InvalidTaskTransition,
    JobNotFound,
    ProblemError,
    ProviderNotFound,
    ProviderTimeoutError as ProviderTimeoutError,
    SchemaConflict,
    TaskNotFound,
    WorkerNotFound,
    problem_exception_handler,
)
from zndraw_joblib.models import (
    Job,
    ProviderRecord,
    Task,
    TaskStatus,
    Worker,
    WorkerJobLink,
)
from zndraw_joblib.provider import Provider
from zndraw_joblib.registry import (
    InternalExecutor,
    InternalProviderExecutor,
    InternalProviderRegistry,
    InternalRegistry,
    ensure_internal_providers,
    register_internal_jobs,
    register_internal_providers,
    register_internal_tasks,
)
from zndraw_joblib.router import router
from zndraw_joblib.schemas import PaginatedResponse
from zndraw_joblib.settings import JobLibSettings
from zndraw_joblib.sweeper import (
    cleanup_stale_workers,
    cleanup_stuck_internal_tasks,
    cleanup_worker,
    run_sweeper,
)

__all__ = [
    "Category",
    "ClaimedTask",
    "Emission",
    "Extension",
    "Forbidden",
    "FrameRoomCleanup",
    "FrameRoomCleanupDep",
    "FrozenEvent",
    "InternalExecutor",
    "InternalJobNotConfigured",
    "InternalProviderExecutor",
    "InternalProviderRegistry",
    "InternalRegistry",
    "InvalidCategory",
    "InvalidRoomId",
    "InvalidTaskTransition",
    "Job",
    "JobLibSettings",
    "JobLibSettingsDep",
    "JobManager",
    "JobNotFound",
    "JobsInvalidate",
    "JoinJobRoom",
    "JoinProviderRoom",
    "LeaveJobRoom",
    "LeaveProviderRoom",
    "PaginatedResponse",
    "ProblemError",
    "Provider",
    "ProviderNotFound",
    "ProviderRecord",
    "ProviderRequest",
    "ProviderResultReady",
    "ProviderTimeoutError",
    "ProvidersInvalidate",
    "ResultBackend",
    "ResultBackendDep",
    "SchemaConflict",
    "Task",
    "TaskAvailable",
    "TaskNotFound",
    "TaskStatus",
    "TaskStatusEvent",
    "Worker",
    "WorkerJobLink",
    "WorkerNotFound",
    "WritableRoomDep",
    "build_task_status_emission",
    "cleanup_stale_workers",
    "cleanup_stuck_internal_tasks",
    "cleanup_worker",
    "emit",
    "ensure_internal_providers",
    "get_frame_room_cleanup",
    "get_joblib_settings",
    "get_result_backend",
    "get_tsio",
    "problem_exception_handler",
    "register_internal_jobs",
    "register_internal_providers",
    "register_internal_tasks",
    "request_hash",
    "router",
    "run_sweeper",
    "validate_room_id",
    "verify_writable_room",
]
